{% set name = "sagemaker_inference" %}
{% set version = "1.5.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cb193713448e4ad26cc3e5652251880b086f2814800b2310c702cb257ce5ec13

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - numpy
    - psutil
    - python >=3.4
    - retrying ==1.3.3
    - scipy
    - six

test:
  imports:
    - sagemaker_inference
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aws/sagemaker-inference-toolkit/
  summary: Open source toolkit for helping create serving containers to run on Amazon SageMaker.
  license: Apache-2.0
  license_family: APACHE
  license_file:
    - LICENSE
    - NOTICE
  doc_url: https://pypi.org/project/sagemaker-inference/
  dev_url: https://github.com/aws/sagemaker-inference-toolkit/

extra:
  recipe-maintainers:
    - mxr-conda
    - mwilson8
    - rluria14
    - benhuff
    - BastianZim
  feedstock-name: sagemaker-inference-toolkit
