{% set name = "sagemaker_inference" %}
{% set version = "1.10.1" %}


package:
  name: {{ name|lower }}-meta
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7aab74809c8eb28c6980eda52cd46e2ca9699a581f291477a0aa3b12ce5e9762

build:
  number: 1

outputs:
  - name: sagemaker-inference
    build:
      noarch: python
    script: build_base.sh
    requirements:
      host:
        - pip
        - python {{ python_min }}
      run:
        - numpy
        - psutil
        - python >={{ python_min }}
        - retrying >=1.3.3,<1.4
        - scipy
        - six
        - boto3
    test:
      imports:
        - sagemaker_inference
      commands:
        - pip check
      requires:
        - pip

  - name: sagemaker-inference-toolkit
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('sagemaker-inference', exact=True) }}
    test:
      imports:
        - sagemaker_inference

  - name: sagemaker_inference
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('sagemaker-inference', exact=True) }}
    test:
      imports:
        - sagemaker_inference


about:
  home: https://github.com/aws/sagemaker-inference-toolkit/
  summary: Open source toolkit for helping create serving containers to run on Amazon SageMaker.
  license: Apache-2.0
  license_family: APACHE
  license_file:
    - LICENSE
    - NOTICE
  doc_url: https://pypi.org/project/sagemaker-inference/
  dev_url: https://github.com/aws/sagemaker-inference-toolkit/

extra:
  recipe-maintainers:
    - mxr-conda
    - mwilson8
    - rluria14
    - benhuff
    - BastianZim
  feedstock-name: sagemaker-inference-toolkit
