{% set name = "sagemaker_inference" %}
{% set version = "1.5.6" %}


package:
  name: {{ name|lower }}-meta
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cb193713448e4ad26cc3e5652251880b086f2814800b2310c702cb257ce5ec13

build:
  number: 0

outputs:
  - name: sagemaker-inference
    build:
      noarch: python
    script: build_base.sh
    requirements:
      host:
        - pip
        - python >=3.4
      run:
        - numpy
        - psutil
        - python >=3.4
        - retrying ==1.3.3
        - scipy
        - six
    test:
      imports:
        - sagemaker_inference
      commands:
        - pip check
      requires:
        - pip

  - name: sagemaker-inference-toolkit
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('sagemaker-inference', exact=True) }}
    test:
      imports:
        - sagemaker_inference

  - name: sagemaker_inference
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('sagemaker-inference', exact=True) }}
    test:
      imports:
        - sagemaker_inference


about:
  home: https://github.com/aws/sagemaker-inference-toolkit/
  summary: Open source toolkit for helping create serving containers to run on Amazon SageMaker.
  license: Apache-2.0
  license_family: APACHE
  license_file:
    - LICENSE
    - NOTICE
  doc_url: https://pypi.org/project/sagemaker-inference/
  dev_url: https://github.com/aws/sagemaker-inference-toolkit/

extra:
  recipe-maintainers:
    - mxr-conda
    - mwilson8
    - rluria14
    - benhuff
    - BastianZim
  feedstock-name: sagemaker-inference-toolkit
